env:
  node: true
rules:
  # - - -
  # node
  node/no-extraneous-import: error
  node/no-extraneous-require: error
  node/no-missing-import: error
  node/no-missing-require: error
  node/no-unpublished-bin: error
  node/no-unpublished-import: error
  node/no-unpublished-require: error
  node/process-exit-as-throw: error
  node/shebang: error
  node/no-deprecated-api: error
  node/exports-style:
    - error
    - module.exports
    - allowBatchAssign: true
