env:
  browser: true
plugins:
  - react
rules:
  # - - -
  # jsx
  react/jsx-boolean-value: error
  # react/jsx-filename-extension: error # react-native does not support .jsx
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  # react/jsx-key: error # ok because lib/ren needs no keys
  # react/jsx-no-bind: warn # todo # ok because lib/ren renders only once
  react/jsx-no-duplicate-props:
    - error
    - ignoreCase: true
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  react/jsx-curly-brace-presence:
    - error
    - never
  react/jsx-pascal-case:
    - error
    - allowAllCaps: true
  react/jsx-uses-react: error
  react/jsx-uses-vars: error

  # - - -
  # react
  react/button-has-type: error
  react/default-props-match-prop-types:
    - error
    - allowRequiredDefaults: true # needed for flow
  react/display-name: warn
  react/forbid-component-props: warn # does not work with react-native # todo
  react/forbid-prop-types: warn # no weak types
  # react/forbid-foreign-prop-types # todo
  react/no-access-state-in-setstate: error
  react/no-array-index-key: error
  react/no-children-prop: error
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: error
  react/no-is-mounted: error
  react/no-redundant-should-component-update: error
  react/no-render-return-value: error
  # react/no-set-state # todo: use with reactive?
  react/no-typos: error
  react/no-string-refs: error
  # react/no-this-in-sfc: error # todo
  react/no-unknown-property: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: error
  react/prefer-stateless-function: warn
  react/prop-types: warn
  react/react-in-jsx-scope: error
  # todo: does not play well with flow
  # react/require-default-props:
  #   - error
  #   - forbidDefaultForRequired: true
  react/require-optimization: warn
  react/require-render-return: error
  react/self-closing-comp: error
  react/style-prop-object: error
  react/void-dom-elements-no-children: error
